limit version of ts-toolbelt to 8.0.x
ts-toolbelt does not compile with 8.4.0, so we should only depend on 8.0

resolves: #13 

```ts
.yarn/cache/ts-toolbelt-npm-8.4.0-f6995cd030-dbc3ad2626.zip/node_modules/ts-toolbelt/out/index.d.ts:983:46 - error TS1110: Type expected.

983     export type NumberOf<N extends number> = `${N}`;
```